# Generated by Django 2.2.9 on 2020-01-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Widget',
        ),
    ]
